[project]
name = "color-mapping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio",
    "diffusers",
    "transformers",
    "controlnet_aux",
    "Pillow",
    "numpy<2.0.0",
]
